version: '3'
services:
  mongo:
    image: mongo
    container_name: 'mongo-database'
    volumes:
      - ~/development/docker/container/mongo-database/data:/data/db
    ports:
      - 27017
    expose:
      - 27017
